config/routes.rb
Projet::Application.routes.draw do
  resources :pieces_commandes

  resources :commandes

  resources :pieces

  resources :roles

  resources :personnes

end

app/models/personne.rb
class Personne < ActiveRecord::Base

has_many :Piece 
has_many :Commande
has_one :Role

end

app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  # GET /personnes
  # GET /personnes.xml
  def index
    @personnes = Personne.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @personnes }
    end
  end

  # GET /personnes/1
  # GET /personnes/1.xml
  def show
    @personne = Personne.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @personne }
    end
  end

  # GET /personnes/new
  # GET /personnes/new.xml
  def new
    @personne = Personne.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @personne }
    end
  end

  # GET /personnes/1/edit
  def edit
    @personne = Personne.find(params[:id])
  end

  # POST /personnes
  # POST /personnes.xml
  def create
    @personne = Personne.new(params[:personne])

    respond_to do |format|
      if @personne.save
        format.html { redirect_to(@personne, :notice => 'Personne was successfully created.') }
        format.xml  { render :xml => @personne, :status => :created, :location => @personne }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @personne.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /personnes/1
  # PUT /personnes/1.xml
  def update
    @personne = Personne.find(params[:id])

    respond_to do |format|
      if @personne.update_attributes(params[:personne])
        format.html { redirect_to(@personne, :notice => 'Personne was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @personne.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.xml
  def destroy
    @personne = Personne.find(params[:id])
    @personne.destroy

    respond_to do |format|
      format.html { redirect_to(personnes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/personnes_helper.rb
module PersonnesHelper
end

app/views/personnes/_form.html.erb
<%= form_for(@personne) do |f| %>
  <% if @personne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personne.errors.count, "error") %> prohibited this personne from being saved:</h2>

      <ul>
      <% @personne.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br />
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personnes/edit.html.erb
<h1>Editing personne</h1>

<%= render 'form' %>

<%= link_to 'Show', @personne %> |
<%= link_to 'Back', personnes_path %>

app/views/personnes/index.html.erb
<h1>Listing personnes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Email</th>
    <th>Telephone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personnes.each do |personne| %>
  <tr>
    <td><%= personne.id %></td>
    <td><%= personne.nom %></td>
    <td><%= personne.prenom %></td>
    <td><%= personne.email %></td>
    <td><%= personne.telephone %></td>
    <td><%= link_to 'Show', personne %></td>
    <td><%= link_to 'Edit', edit_personne_path(personne) %></td>
    <td><%= link_to 'Destroy', personne, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Personne', new_personne_path %>

app/views/personnes/new.html.erb
<h1>New personne</h1>

<%= render 'form' %>

<%= link_to 'Back', personnes_path %>

app/views/personnes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @personne.id %>
</p>

<p>
  <b>Nom:</b>
  <%= @personne.nom %>
</p>

<p>
  <b>Prenom:</b>
  <%= @personne.prenom %>
</p>

<p>
  <b>Email:</b>
  <%= @personne.email %>
</p>

<p>
  <b>Telephone:</b>
  <%= @personne.telephone %>
</p>


<%= link_to 'Edit', edit_personne_path(@personne) %> |
<%= link_to 'Back', personnes_path %>