config/routes.rb
Projet::Application.routes.draw do
  resources :pieces_commandes

  resources :commandes

  resources :pieces

  resources :roles

  resources :personnes

end

app/models/pieces_commande.rb
class PiecesCommande < ActiveRecord::Base

has_one :Commande
has_one :Piece

end

app/controllers/pieces_commandes_controller.rb
class PiecesCommandesController < ApplicationController
  # GET /pieces_commandes
  # GET /pieces_commandes.xml
  def index
    @pieces_commandes = PiecesCommande.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pieces_commandes }
    end
  end

  # GET /pieces_commandes/1
  # GET /pieces_commandes/1.xml
  def show
    @pieces_commande = PiecesCommande.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pieces_commande }
    end
  end

  # GET /pieces_commandes/new
  # GET /pieces_commandes/new.xml
  def new
    @pieces_commande = PiecesCommande.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pieces_commande }
    end
  end

  # GET /pieces_commandes/1/edit
  def edit
    @pieces_commande = PiecesCommande.find(params[:id])
  end

  # POST /pieces_commandes
  # POST /pieces_commandes.xml
  def create
    @pieces_commande = PiecesCommande.new(params[:pieces_commande])

    respond_to do |format|
      if @pieces_commande.save
        format.html { redirect_to(@pieces_commande, :notice => 'Pieces commande was successfully created.') }
        format.xml  { render :xml => @pieces_commande, :status => :created, :location => @pieces_commande }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pieces_commande.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pieces_commandes/1
  # PUT /pieces_commandes/1.xml
  def update
    @pieces_commande = PiecesCommande.find(params[:id])

    respond_to do |format|
      if @pieces_commande.update_attributes(params[:pieces_commande])
        format.html { redirect_to(@pieces_commande, :notice => 'Pieces commande was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pieces_commande.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces_commandes/1
  # DELETE /pieces_commandes/1.xml
  def destroy
    @pieces_commande = PiecesCommande.find(params[:id])
    @pieces_commande.destroy

    respond_to do |format|
      format.html { redirect_to(pieces_commandes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pieces_commandes_helper.rb
module PiecesCommandesHelper
end

app/views/pieces_commandes/_form.html.erb
<%= form_for(@pieces_commande) do |f| %>
  <% if @pieces_commande.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pieces_commande.errors.count, "error") %> prohibited this pieces_commande from being saved:</h2>

      <ul>
      <% @pieces_commande.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_commande %><br />
    <%= f.text_field :id_commande %>
  </div>
  <div class="field">
    <%= f.label :id_piece %><br />
    <%= f.text_field :id_piece %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces_commandes/edit.html.erb
<h1>Editing pieces_commande</h1>

<%= render 'form' %>

<%= link_to 'Show', @pieces_commande %> |
<%= link_to 'Back', pieces_commandes_path %>

app/views/pieces_commandes/index.html.erb
<h1>Listing pieces_commandes</h1>

<table>
  <tr>
    <th>Id commande</th>
    <th>Id piece</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pieces_commandes.each do |pieces_commande| %>
  <tr>
    <td><%= pieces_commande.id_commande %></td>
    <td><%= pieces_commande.id_piece %></td>
    <td><%= link_to 'Show', pieces_commande %></td>
    <td><%= link_to 'Edit', edit_pieces_commande_path(pieces_commande) %></td>
    <td><%= link_to 'Destroy', pieces_commande, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pieces commande', new_pieces_commande_path %>

app/views/pieces_commandes/new.html.erb
<h1>New pieces_commande</h1>

<%= render 'form' %>

<%= link_to 'Back', pieces_commandes_path %>

app/views/pieces_commandes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id commande:</b>
  <%= @pieces_commande.id_commande %>
</p>

<p>
  <b>Id piece:</b>
  <%= @pieces_commande.id_piece %>
</p>


<%= link_to 'Edit', edit_pieces_commande_path(@pieces_commande) %> |
<%= link_to 'Back', pieces_commandes_path %>