config/routes.rb
Projet::Application.routes.draw do
  resources :pieces_commandes

  resources :commandes

  resources :pieces

  resources :roles

  resources :personnes

end

app/models/commande.rb
class Commande < ActiveRecord::Base

has_one :Personne
has_many :Piece

end

app/controllers/commandes_controller.rb
class CommandesController < ApplicationController
  # GET /commandes
  # GET /commandes.xml
  def index
    @commandes = Commande.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @commandes }
    end
  end

  # GET /commandes/1
  # GET /commandes/1.xml
  def show
    @commande = Commande.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @commande }
    end
  end

  # GET /commandes/new
  # GET /commandes/new.xml
  def new
    @commande = Commande.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @commande }
    end
  end

  # GET /commandes/1/edit
  def edit
    @commande = Commande.find(params[:id])
  end

  # POST /commandes
  # POST /commandes.xml
  def create
    @commande = Commande.new(params[:commande])

    respond_to do |format|
      if @commande.save
        format.html { redirect_to(@commande, :notice => 'Commande was successfully created.') }
        format.xml  { render :xml => @commande, :status => :created, :location => @commande }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @commande.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commandes/1
  # PUT /commandes/1.xml
  def update
    @commande = Commande.find(params[:id])

    respond_to do |format|
      if @commande.update_attributes(params[:commande])
        format.html { redirect_to(@commande, :notice => 'Commande was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @commande.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commandes/1
  # DELETE /commandes/1.xml
  def destroy
    @commande = Commande.find(params[:id])
    @commande.destroy

    respond_to do |format|
      format.html { redirect_to(commandes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/commandes_helper.rb
module CommandesHelper
end

app/views/commandes/_form.html.erb
<%= form_for(@commande) do |f| %>
  <% if @commande.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commande.errors.count, "error") %> prohibited this commande from being saved:</h2>

      <ul>
      <% @commande.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :qte %><br />
    <%= f.text_field :qte %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commandes/edit.html.erb
<h1>Editing commande</h1>

<%= render 'form' %>

<%= link_to 'Show', @commande %> |
<%= link_to 'Back', commandes_path %>

app/views/commandes/index.html.erb
<h1>Listing commandes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Date</th>
    <th>Qte</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commandes.each do |commande| %>
  <tr>
    <td><%= commande.id %></td>
    <td><%= commande.date %></td>
    <td><%= commande.qte %></td>
    <td><%= link_to 'Show', commande %></td>
    <td><%= link_to 'Edit', edit_commande_path(commande) %></td>
    <td><%= link_to 'Destroy', commande, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commande', new_commande_path %>

app/views/commandes/new.html.erb
<h1>New commande</h1>

<%= render 'form' %>

<%= link_to 'Back', commandes_path %>

app/views/commandes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @commande.id %>
</p>

<p>
  <b>Date:</b>
  <%= @commande.date %>
</p>

<p>
  <b>Qte:</b>
  <%= @commande.qte %>
</p>


<%= link_to 'Edit', edit_commande_path(@commande) %> |
<%= link_to 'Back', commandes_path %>